# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 21:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(blank=True, max_length=200, null=True)),
                ('make', models.CharField(blank=True, max_length=200, null=True)),
                ('model', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('user_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('has_portfolios', models.BooleanField()),
                ('portfolio_url', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('photographer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Addresses', serialize=False, to='imager_profile.Photographer')),
                ('address_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Street Address 1')),
                ('address_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Street Address 2')),
                ('city', models.CharField(blank=True, max_length=128, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=2, null=True, verbose_name='State')),
                ('post_code', models.CharField(blank=True, max_length=7, null=True, verbose_name='Zip Code')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('photographer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='SocialMedia', serialize=False, to='imager_profile.Photographer')),
            ],
        ),
        migrations.AddField(
            model_name='photographer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
