# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 00:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='photographer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='imager_profile.Photographer'),
        ),
    ]
