# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='title',
            field=models.CharField(blank=True, default='pirmary camera', max_length=255, verbose_name='Title'),
        ),
    ]
