# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0002_auto_20160927_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='bio',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Bio'),
        ),
    ]
