# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0002_model_edits'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='reason_i_like_bacon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='has_portfolios',
            field=models.BooleanField(default=False),
        ),
    ]
