# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0003_auto_20160921_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='photographer_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Addresses', serialize=False, to='imager_profile.Photographer'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='photographer_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='SocialMedia', serialize=False, to='imager_profile.Photographer'),
        ),
    ]
