# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 02:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='published',
            field=models.CharField(choices=[('private', 'private'), ('shared', 'shared'), ('public', 'public')], default='private', max_length=64),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photographer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='imager_profile.Photographer'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='published',
            field=models.CharField(choices=[('private', 'private'), ('shared', 'shared'), ('public', 'public')], default='private', max_length=64),
        ),
    ]
