# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 23:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='date_pub',
        ),
    ]
