# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='albums',
            field=models.ManyToManyField(blank=True, null=True, related_name='photos', to='imager_images.Album'),
        ),
    ]
