# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='date_pub',
            field=models.DateField(blank=True, null=True, verbose_name='Date Published'),
        ),
    ]
