# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 23:57
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0002_auto_20160930_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='id',
        ),
        migrations.AddField(
            model_name='album',
            name='album_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
