# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0002_auto_20160927_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='date_pub',
            field=models.DateField(blank=True, null=True, verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
    ]
