# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0003_auto_20160927_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='albums',
            field=models.ManyToManyField(related_name='photos', to='imager_images.Album'),
        ),
    ]
